### ISSUE TITLE
VIDIOC_QUERYCAP failure

### ISSUE THREAD

**Issue by lchop** [econsystems/rqt_cam#1]
Hello,

I am trying to use this package with my econ-system setup. I could build the package, but I could not get the frame of the camera. I got these errors when I try to launch:

=============== Video devices detected ===============
[ INFO] [1611051724.454421895]: 1.vi_output__eimx290_35_0042

[ INFO] [1611051724.454531688]: 2.vi_output__eimx290_32_0042

[ INFO] [1611051724.454621481]: 3.vi_output__eimx290_34_0042

[ INFO] [1611051724.454743979]: 4.vi_output__eimx290_30_0042

[ INFO] [1611051811.368519470]:  VIDIOC_QUERYCAP failure
[ INFO] [1611051811.385181570]:  VIDIOC_QUERYCAP failure
[ INFO] [1611051811.396448300]:  VIDIOC_QUERYCAP failure
[ INFO] [1611051811.396685286]:  VIDIOC_QUERYCAP failure
[ INFO] [1611051811.396832362]:  VIDIOC_QUERYCAP failure
[ INFO] [1611051811.408009693]:  VIDIOC_QUERYCAP failure
[ INFO] [1611051811.419311183]:  VIDIOC_QUERYCAP failure
[ INFO] [1611051811.419529413]:  VIDIOC_QUERYCAP failure

Could you help me ?

**Comment by Ramsonjehu** [comment]
Hi @lchop , IMX290 camera will use Nvidia ISP and we can capture frames only through Argus library. We cant access this camera through V4L2 APIs. I hope that may be the reason for this error. 
In future, Nvidia is planning to support v4L2 APIs for ISP cameras in upcoming release, once that BSP released we will add support the same for IMX290 camera then you can use ROS on top of that.
